// Generated by gencpp from file flexcraft_msgs/ArmGoal.msg
// DO NOT EDIT!


#ifndef FLEXCRAFT_MSGS_MESSAGE_ARMGOAL_H
#define FLEXCRAFT_MSGS_MESSAGE_ARMGOAL_H

#include <ros/service_traits.h>


#include <flexcraft_msgs/ArmGoalRequest.h>
#include <flexcraft_msgs/ArmGoalResponse.h>


namespace flexcraft_msgs
{

struct ArmGoal
{

typedef ArmGoalRequest Request;
typedef ArmGoalResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ArmGoal
} // namespace flexcraft_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::flexcraft_msgs::ArmGoal > {
  static const char* value()
  {
    return "5d29b6219247a57177fcffb880bc2f7e";
  }

  static const char* value(const ::flexcraft_msgs::ArmGoal&) { return value(); }
};

template<>
struct DataType< ::flexcraft_msgs::ArmGoal > {
  static const char* value()
  {
    return "flexcraft_msgs/ArmGoal";
  }

  static const char* value(const ::flexcraft_msgs::ArmGoal&) { return value(); }
};


// service_traits::MD5Sum< ::flexcraft_msgs::ArmGoalRequest> should match
// service_traits::MD5Sum< ::flexcraft_msgs::ArmGoal >
template<>
struct MD5Sum< ::flexcraft_msgs::ArmGoalRequest>
{
  static const char* value()
  {
    return MD5Sum< ::flexcraft_msgs::ArmGoal >::value();
  }
  static const char* value(const ::flexcraft_msgs::ArmGoalRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::flexcraft_msgs::ArmGoalRequest> should match
// service_traits::DataType< ::flexcraft_msgs::ArmGoal >
template<>
struct DataType< ::flexcraft_msgs::ArmGoalRequest>
{
  static const char* value()
  {
    return DataType< ::flexcraft_msgs::ArmGoal >::value();
  }
  static const char* value(const ::flexcraft_msgs::ArmGoalRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::flexcraft_msgs::ArmGoalResponse> should match
// service_traits::MD5Sum< ::flexcraft_msgs::ArmGoal >
template<>
struct MD5Sum< ::flexcraft_msgs::ArmGoalResponse>
{
  static const char* value()
  {
    return MD5Sum< ::flexcraft_msgs::ArmGoal >::value();
  }
  static const char* value(const ::flexcraft_msgs::ArmGoalResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::flexcraft_msgs::ArmGoalResponse> should match
// service_traits::DataType< ::flexcraft_msgs::ArmGoal >
template<>
struct DataType< ::flexcraft_msgs::ArmGoalResponse>
{
  static const char* value()
  {
    return DataType< ::flexcraft_msgs::ArmGoal >::value();
  }
  static const char* value(const ::flexcraft_msgs::ArmGoalResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // FLEXCRAFT_MSGS_MESSAGE_ARMGOAL_H
