// Generated by gencpp from file flexcraft_msgs/ArmGoalRequest.msg
// DO NOT EDIT!


#ifndef FLEXCRAFT_MSGS_MESSAGE_ARMGOALREQUEST_H
#define FLEXCRAFT_MSGS_MESSAGE_ARMGOALREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose.h>

namespace flexcraft_msgs
{
template <class ContainerAllocator>
struct ArmGoalRequest_
{
  typedef ArmGoalRequest_<ContainerAllocator> Type;

  ArmGoalRequest_()
    : goal_pose()  {
    }
  ArmGoalRequest_(const ContainerAllocator& _alloc)
    : goal_pose(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _goal_pose_type;
  _goal_pose_type goal_pose;





  typedef boost::shared_ptr< ::flexcraft_msgs::ArmGoalRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::flexcraft_msgs::ArmGoalRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ArmGoalRequest_

typedef ::flexcraft_msgs::ArmGoalRequest_<std::allocator<void> > ArmGoalRequest;

typedef boost::shared_ptr< ::flexcraft_msgs::ArmGoalRequest > ArmGoalRequestPtr;
typedef boost::shared_ptr< ::flexcraft_msgs::ArmGoalRequest const> ArmGoalRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::flexcraft_msgs::ArmGoalRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::flexcraft_msgs::ArmGoalRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::flexcraft_msgs::ArmGoalRequest_<ContainerAllocator1> & lhs, const ::flexcraft_msgs::ArmGoalRequest_<ContainerAllocator2> & rhs)
{
  return lhs.goal_pose == rhs.goal_pose;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::flexcraft_msgs::ArmGoalRequest_<ContainerAllocator1> & lhs, const ::flexcraft_msgs::ArmGoalRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace flexcraft_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::flexcraft_msgs::ArmGoalRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::flexcraft_msgs::ArmGoalRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::flexcraft_msgs::ArmGoalRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::flexcraft_msgs::ArmGoalRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::flexcraft_msgs::ArmGoalRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::flexcraft_msgs::ArmGoalRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::flexcraft_msgs::ArmGoalRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "703d9fa1b50df73e1eb3a62a925392a1";
  }

  static const char* value(const ::flexcraft_msgs::ArmGoalRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x703d9fa1b50df73eULL;
  static const uint64_t static_value2 = 0x1eb3a62a925392a1ULL;
};

template<class ContainerAllocator>
struct DataType< ::flexcraft_msgs::ArmGoalRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "flexcraft_msgs/ArmGoalRequest";
  }

  static const char* value(const ::flexcraft_msgs::ArmGoalRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::flexcraft_msgs::ArmGoalRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Pose goal_pose\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::flexcraft_msgs::ArmGoalRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::flexcraft_msgs::ArmGoalRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.goal_pose);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ArmGoalRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::flexcraft_msgs::ArmGoalRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::flexcraft_msgs::ArmGoalRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "goal_pose: ";
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.goal_pose);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FLEXCRAFT_MSGS_MESSAGE_ARMGOALREQUEST_H
