// Generated by gencpp from file flexcraft_msgs/ClusterOctomapRequest.msg
// DO NOT EDIT!


#ifndef FLEXCRAFT_MSGS_MESSAGE_CLUSTEROCTOMAPREQUEST_H
#define FLEXCRAFT_MSGS_MESSAGE_CLUSTEROCTOMAPREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point.h>

namespace flexcraft_msgs
{
template <class ContainerAllocator>
struct ClusterOctomapRequest_
{
  typedef ClusterOctomapRequest_<ContainerAllocator> Type;

  ClusterOctomapRequest_()
    : cloud()  {
    }
  ClusterOctomapRequest_(const ContainerAllocator& _alloc)
    : cloud(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::geometry_msgs::Point_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::geometry_msgs::Point_<ContainerAllocator> >> _cloud_type;
  _cloud_type cloud;





  typedef boost::shared_ptr< ::flexcraft_msgs::ClusterOctomapRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::flexcraft_msgs::ClusterOctomapRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ClusterOctomapRequest_

typedef ::flexcraft_msgs::ClusterOctomapRequest_<std::allocator<void> > ClusterOctomapRequest;

typedef boost::shared_ptr< ::flexcraft_msgs::ClusterOctomapRequest > ClusterOctomapRequestPtr;
typedef boost::shared_ptr< ::flexcraft_msgs::ClusterOctomapRequest const> ClusterOctomapRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::flexcraft_msgs::ClusterOctomapRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::flexcraft_msgs::ClusterOctomapRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::flexcraft_msgs::ClusterOctomapRequest_<ContainerAllocator1> & lhs, const ::flexcraft_msgs::ClusterOctomapRequest_<ContainerAllocator2> & rhs)
{
  return lhs.cloud == rhs.cloud;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::flexcraft_msgs::ClusterOctomapRequest_<ContainerAllocator1> & lhs, const ::flexcraft_msgs::ClusterOctomapRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace flexcraft_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::flexcraft_msgs::ClusterOctomapRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::flexcraft_msgs::ClusterOctomapRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::flexcraft_msgs::ClusterOctomapRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::flexcraft_msgs::ClusterOctomapRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::flexcraft_msgs::ClusterOctomapRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::flexcraft_msgs::ClusterOctomapRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::flexcraft_msgs::ClusterOctomapRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a8c6ea05d9d0285735642845df1b7b8c";
  }

  static const char* value(const ::flexcraft_msgs::ClusterOctomapRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa8c6ea05d9d02857ULL;
  static const uint64_t static_value2 = 0x35642845df1b7b8cULL;
};

template<class ContainerAllocator>
struct DataType< ::flexcraft_msgs::ClusterOctomapRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "flexcraft_msgs/ClusterOctomapRequest";
  }

  static const char* value(const ::flexcraft_msgs::ClusterOctomapRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::flexcraft_msgs::ClusterOctomapRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Octomap converted to points\n"
"geometry_msgs/Point[] cloud\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::flexcraft_msgs::ClusterOctomapRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::flexcraft_msgs::ClusterOctomapRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.cloud);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ClusterOctomapRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::flexcraft_msgs::ClusterOctomapRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::flexcraft_msgs::ClusterOctomapRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "cloud: ";
    if (v.cloud.empty() || false)
      s << "[";
    for (size_t i = 0; i < v.cloud.size(); ++i)
    {
      if (false && i > 0)
        s << ", ";
      else if (!false)
        s << std::endl << indent << "  -";
      Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, false ? std::string() : indent + "    ", v.cloud[i]);
    }
    if (v.cloud.empty() || false)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // FLEXCRAFT_MSGS_MESSAGE_CLUSTEROCTOMAPREQUEST_H
