// Generated by gencpp from file flexcraft_msgs/ClusterOctomap.msg
// DO NOT EDIT!


#ifndef FLEXCRAFT_MSGS_MESSAGE_CLUSTEROCTOMAP_H
#define FLEXCRAFT_MSGS_MESSAGE_CLUSTEROCTOMAP_H

#include <ros/service_traits.h>


#include <flexcraft_msgs/ClusterOctomapRequest.h>
#include <flexcraft_msgs/ClusterOctomapResponse.h>


namespace flexcraft_msgs
{

struct ClusterOctomap
{

typedef ClusterOctomapRequest Request;
typedef ClusterOctomapResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ClusterOctomap
} // namespace flexcraft_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::flexcraft_msgs::ClusterOctomap > {
  static const char* value()
  {
    return "0ff5ab34ceb3d552b78858a9555a8a79";
  }

  static const char* value(const ::flexcraft_msgs::ClusterOctomap&) { return value(); }
};

template<>
struct DataType< ::flexcraft_msgs::ClusterOctomap > {
  static const char* value()
  {
    return "flexcraft_msgs/ClusterOctomap";
  }

  static const char* value(const ::flexcraft_msgs::ClusterOctomap&) { return value(); }
};


// service_traits::MD5Sum< ::flexcraft_msgs::ClusterOctomapRequest> should match
// service_traits::MD5Sum< ::flexcraft_msgs::ClusterOctomap >
template<>
struct MD5Sum< ::flexcraft_msgs::ClusterOctomapRequest>
{
  static const char* value()
  {
    return MD5Sum< ::flexcraft_msgs::ClusterOctomap >::value();
  }
  static const char* value(const ::flexcraft_msgs::ClusterOctomapRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::flexcraft_msgs::ClusterOctomapRequest> should match
// service_traits::DataType< ::flexcraft_msgs::ClusterOctomap >
template<>
struct DataType< ::flexcraft_msgs::ClusterOctomapRequest>
{
  static const char* value()
  {
    return DataType< ::flexcraft_msgs::ClusterOctomap >::value();
  }
  static const char* value(const ::flexcraft_msgs::ClusterOctomapRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::flexcraft_msgs::ClusterOctomapResponse> should match
// service_traits::MD5Sum< ::flexcraft_msgs::ClusterOctomap >
template<>
struct MD5Sum< ::flexcraft_msgs::ClusterOctomapResponse>
{
  static const char* value()
  {
    return MD5Sum< ::flexcraft_msgs::ClusterOctomap >::value();
  }
  static const char* value(const ::flexcraft_msgs::ClusterOctomapResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::flexcraft_msgs::ClusterOctomapResponse> should match
// service_traits::DataType< ::flexcraft_msgs::ClusterOctomap >
template<>
struct DataType< ::flexcraft_msgs::ClusterOctomapResponse>
{
  static const char* value()
  {
    return DataType< ::flexcraft_msgs::ClusterOctomap >::value();
  }
  static const char* value(const ::flexcraft_msgs::ClusterOctomapResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // FLEXCRAFT_MSGS_MESSAGE_CLUSTEROCTOMAP_H
