// Generated by gencpp from file flexcraft_msgs/ComputeNBVRequest.msg
// DO NOT EDIT!


#ifndef FLEXCRAFT_MSGS_MESSAGE_COMPUTENBVREQUEST_H
#define FLEXCRAFT_MSGS_MESSAGE_COMPUTENBVREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/PoseArray.h>
#include <geometry_msgs/Point.h>
#include <geometry_msgs/Point.h>

namespace flexcraft_msgs
{
template <class ContainerAllocator>
struct ComputeNBVRequest_
{
  typedef ComputeNBVRequest_<ContainerAllocator> Type;

  ComputeNBVRequest_()
    : candidates()
    , bbx_centers()
    , bbx_sizes()
    , class_id(0)  {
    }
  ComputeNBVRequest_(const ContainerAllocator& _alloc)
    : candidates(_alloc)
    , bbx_centers(_alloc)
    , bbx_sizes(_alloc)
    , class_id(0)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::PoseArray_<ContainerAllocator>  _candidates_type;
  _candidates_type candidates;

   typedef std::vector< ::geometry_msgs::Point_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::geometry_msgs::Point_<ContainerAllocator> >> _bbx_centers_type;
  _bbx_centers_type bbx_centers;

   typedef std::vector< ::geometry_msgs::Point_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::geometry_msgs::Point_<ContainerAllocator> >> _bbx_sizes_type;
  _bbx_sizes_type bbx_sizes;

   typedef int32_t _class_id_type;
  _class_id_type class_id;





  typedef boost::shared_ptr< ::flexcraft_msgs::ComputeNBVRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::flexcraft_msgs::ComputeNBVRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ComputeNBVRequest_

typedef ::flexcraft_msgs::ComputeNBVRequest_<std::allocator<void> > ComputeNBVRequest;

typedef boost::shared_ptr< ::flexcraft_msgs::ComputeNBVRequest > ComputeNBVRequestPtr;
typedef boost::shared_ptr< ::flexcraft_msgs::ComputeNBVRequest const> ComputeNBVRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::flexcraft_msgs::ComputeNBVRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::flexcraft_msgs::ComputeNBVRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::flexcraft_msgs::ComputeNBVRequest_<ContainerAllocator1> & lhs, const ::flexcraft_msgs::ComputeNBVRequest_<ContainerAllocator2> & rhs)
{
  return lhs.candidates == rhs.candidates &&
    lhs.bbx_centers == rhs.bbx_centers &&
    lhs.bbx_sizes == rhs.bbx_sizes &&
    lhs.class_id == rhs.class_id;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::flexcraft_msgs::ComputeNBVRequest_<ContainerAllocator1> & lhs, const ::flexcraft_msgs::ComputeNBVRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace flexcraft_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::flexcraft_msgs::ComputeNBVRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::flexcraft_msgs::ComputeNBVRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::flexcraft_msgs::ComputeNBVRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::flexcraft_msgs::ComputeNBVRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::flexcraft_msgs::ComputeNBVRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::flexcraft_msgs::ComputeNBVRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::flexcraft_msgs::ComputeNBVRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bbfb37c94fd0934978627014d83729ec";
  }

  static const char* value(const ::flexcraft_msgs::ComputeNBVRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbbfb37c94fd09349ULL;
  static const uint64_t static_value2 = 0x78627014d83729ecULL;
};

template<class ContainerAllocator>
struct DataType< ::flexcraft_msgs::ComputeNBVRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "flexcraft_msgs/ComputeNBVRequest";
  }

  static const char* value(const ::flexcraft_msgs::ComputeNBVRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::flexcraft_msgs::ComputeNBVRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/PoseArray candidates\n"
"geometry_msgs/Point[] bbx_centers\n"
"geometry_msgs/Point[] bbx_sizes\n"
"int32 class_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/PoseArray\n"
"# An array of poses with a header for global reference.\n"
"\n"
"Header header\n"
"\n"
"Pose[] poses\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::flexcraft_msgs::ComputeNBVRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::flexcraft_msgs::ComputeNBVRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.candidates);
      stream.next(m.bbx_centers);
      stream.next(m.bbx_sizes);
      stream.next(m.class_id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ComputeNBVRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::flexcraft_msgs::ComputeNBVRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::flexcraft_msgs::ComputeNBVRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "candidates: ";
    Printer< ::geometry_msgs::PoseArray_<ContainerAllocator> >::stream(s, indent + "  ", v.candidates);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "bbx_centers: ";
    if (v.bbx_centers.empty() || false)
      s << "[";
    for (size_t i = 0; i < v.bbx_centers.size(); ++i)
    {
      if (false && i > 0)
        s << ", ";
      else if (!false)
        s << std::endl << indent << "  -";
      Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, false ? std::string() : indent + "    ", v.bbx_centers[i]);
    }
    if (v.bbx_centers.empty() || false)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "bbx_sizes: ";
    if (v.bbx_sizes.empty() || false)
      s << "[";
    for (size_t i = 0; i < v.bbx_sizes.size(); ++i)
    {
      if (false && i > 0)
        s << ", ";
      else if (!false)
        s << std::endl << indent << "  -";
      Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, false ? std::string() : indent + "    ", v.bbx_sizes[i]);
    }
    if (v.bbx_sizes.empty() || false)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "class_id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.class_id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FLEXCRAFT_MSGS_MESSAGE_COMPUTENBVREQUEST_H
