// Generated by gencpp from file flexcraft_msgs/ComputeNBV.msg
// DO NOT EDIT!


#ifndef FLEXCRAFT_MSGS_MESSAGE_COMPUTENBV_H
#define FLEXCRAFT_MSGS_MESSAGE_COMPUTENBV_H

#include <ros/service_traits.h>


#include <flexcraft_msgs/ComputeNBVRequest.h>
#include <flexcraft_msgs/ComputeNBVResponse.h>


namespace flexcraft_msgs
{

struct ComputeNBV
{

typedef ComputeNBVRequest Request;
typedef ComputeNBVResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ComputeNBV
} // namespace flexcraft_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::flexcraft_msgs::ComputeNBV > {
  static const char* value()
  {
    return "ce14f1e75e40af74df5ebd698c79385b";
  }

  static const char* value(const ::flexcraft_msgs::ComputeNBV&) { return value(); }
};

template<>
struct DataType< ::flexcraft_msgs::ComputeNBV > {
  static const char* value()
  {
    return "flexcraft_msgs/ComputeNBV";
  }

  static const char* value(const ::flexcraft_msgs::ComputeNBV&) { return value(); }
};


// service_traits::MD5Sum< ::flexcraft_msgs::ComputeNBVRequest> should match
// service_traits::MD5Sum< ::flexcraft_msgs::ComputeNBV >
template<>
struct MD5Sum< ::flexcraft_msgs::ComputeNBVRequest>
{
  static const char* value()
  {
    return MD5Sum< ::flexcraft_msgs::ComputeNBV >::value();
  }
  static const char* value(const ::flexcraft_msgs::ComputeNBVRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::flexcraft_msgs::ComputeNBVRequest> should match
// service_traits::DataType< ::flexcraft_msgs::ComputeNBV >
template<>
struct DataType< ::flexcraft_msgs::ComputeNBVRequest>
{
  static const char* value()
  {
    return DataType< ::flexcraft_msgs::ComputeNBV >::value();
  }
  static const char* value(const ::flexcraft_msgs::ComputeNBVRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::flexcraft_msgs::ComputeNBVResponse> should match
// service_traits::MD5Sum< ::flexcraft_msgs::ComputeNBV >
template<>
struct MD5Sum< ::flexcraft_msgs::ComputeNBVResponse>
{
  static const char* value()
  {
    return MD5Sum< ::flexcraft_msgs::ComputeNBV >::value();
  }
  static const char* value(const ::flexcraft_msgs::ComputeNBVResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::flexcraft_msgs::ComputeNBVResponse> should match
// service_traits::DataType< ::flexcraft_msgs::ComputeNBV >
template<>
struct DataType< ::flexcraft_msgs::ComputeNBVResponse>
{
  static const char* value()
  {
    return DataType< ::flexcraft_msgs::ComputeNBV >::value();
  }
  static const char* value(const ::flexcraft_msgs::ComputeNBVResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // FLEXCRAFT_MSGS_MESSAGE_COMPUTENBV_H
