// Generated by gencpp from file flexcraft_msgs/ComputeNBVResponse.msg
// DO NOT EDIT!


#ifndef FLEXCRAFT_MSGS_MESSAGE_COMPUTENBVRESPONSE_H
#define FLEXCRAFT_MSGS_MESSAGE_COMPUTENBVRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose.h>

namespace flexcraft_msgs
{
template <class ContainerAllocator>
struct ComputeNBVResponse_
{
  typedef ComputeNBVResponse_<ContainerAllocator> Type;

  ComputeNBVResponse_()
    : nbv_pose()
    , nbv_index(0)
    , success(false)  {
    }
  ComputeNBVResponse_(const ContainerAllocator& _alloc)
    : nbv_pose(_alloc)
    , nbv_index(0)
    , success(false)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _nbv_pose_type;
  _nbv_pose_type nbv_pose;

   typedef int32_t _nbv_index_type;
  _nbv_index_type nbv_index;

   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::flexcraft_msgs::ComputeNBVResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::flexcraft_msgs::ComputeNBVResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ComputeNBVResponse_

typedef ::flexcraft_msgs::ComputeNBVResponse_<std::allocator<void> > ComputeNBVResponse;

typedef boost::shared_ptr< ::flexcraft_msgs::ComputeNBVResponse > ComputeNBVResponsePtr;
typedef boost::shared_ptr< ::flexcraft_msgs::ComputeNBVResponse const> ComputeNBVResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::flexcraft_msgs::ComputeNBVResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::flexcraft_msgs::ComputeNBVResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::flexcraft_msgs::ComputeNBVResponse_<ContainerAllocator1> & lhs, const ::flexcraft_msgs::ComputeNBVResponse_<ContainerAllocator2> & rhs)
{
  return lhs.nbv_pose == rhs.nbv_pose &&
    lhs.nbv_index == rhs.nbv_index &&
    lhs.success == rhs.success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::flexcraft_msgs::ComputeNBVResponse_<ContainerAllocator1> & lhs, const ::flexcraft_msgs::ComputeNBVResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace flexcraft_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::flexcraft_msgs::ComputeNBVResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::flexcraft_msgs::ComputeNBVResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::flexcraft_msgs::ComputeNBVResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::flexcraft_msgs::ComputeNBVResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::flexcraft_msgs::ComputeNBVResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::flexcraft_msgs::ComputeNBVResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::flexcraft_msgs::ComputeNBVResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "feeb8d2b0d0525de437e3fe9d317f4c5";
  }

  static const char* value(const ::flexcraft_msgs::ComputeNBVResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xfeeb8d2b0d0525deULL;
  static const uint64_t static_value2 = 0x437e3fe9d317f4c5ULL;
};

template<class ContainerAllocator>
struct DataType< ::flexcraft_msgs::ComputeNBVResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "flexcraft_msgs/ComputeNBVResponse";
  }

  static const char* value(const ::flexcraft_msgs::ComputeNBVResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::flexcraft_msgs::ComputeNBVResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Pose nbv_pose\n"
"int32 nbv_index\n"
"bool success\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::flexcraft_msgs::ComputeNBVResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::flexcraft_msgs::ComputeNBVResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.nbv_pose);
      stream.next(m.nbv_index);
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ComputeNBVResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::flexcraft_msgs::ComputeNBVResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::flexcraft_msgs::ComputeNBVResponse_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "nbv_pose: ";
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.nbv_pose);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "nbv_index: ";
    Printer<int32_t>::stream(s, indent + "  ", v.nbv_index);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FLEXCRAFT_MSGS_MESSAGE_COMPUTENBVRESPONSE_H
