// Generated by gencpp from file flexcraft_msgs/GetPcl.msg
// DO NOT EDIT!


#ifndef FLEXCRAFT_MSGS_MESSAGE_GETPCL_H
#define FLEXCRAFT_MSGS_MESSAGE_GETPCL_H

#include <ros/service_traits.h>


#include <flexcraft_msgs/GetPclRequest.h>
#include <flexcraft_msgs/GetPclResponse.h>


namespace flexcraft_msgs
{

struct GetPcl
{

typedef GetPclRequest Request;
typedef GetPclResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetPcl
} // namespace flexcraft_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::flexcraft_msgs::GetPcl > {
  static const char* value()
  {
    return "6675bded5f9acf2f2266e0dd468b6db0";
  }

  static const char* value(const ::flexcraft_msgs::GetPcl&) { return value(); }
};

template<>
struct DataType< ::flexcraft_msgs::GetPcl > {
  static const char* value()
  {
    return "flexcraft_msgs/GetPcl";
  }

  static const char* value(const ::flexcraft_msgs::GetPcl&) { return value(); }
};


// service_traits::MD5Sum< ::flexcraft_msgs::GetPclRequest> should match
// service_traits::MD5Sum< ::flexcraft_msgs::GetPcl >
template<>
struct MD5Sum< ::flexcraft_msgs::GetPclRequest>
{
  static const char* value()
  {
    return MD5Sum< ::flexcraft_msgs::GetPcl >::value();
  }
  static const char* value(const ::flexcraft_msgs::GetPclRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::flexcraft_msgs::GetPclRequest> should match
// service_traits::DataType< ::flexcraft_msgs::GetPcl >
template<>
struct DataType< ::flexcraft_msgs::GetPclRequest>
{
  static const char* value()
  {
    return DataType< ::flexcraft_msgs::GetPcl >::value();
  }
  static const char* value(const ::flexcraft_msgs::GetPclRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::flexcraft_msgs::GetPclResponse> should match
// service_traits::MD5Sum< ::flexcraft_msgs::GetPcl >
template<>
struct MD5Sum< ::flexcraft_msgs::GetPclResponse>
{
  static const char* value()
  {
    return MD5Sum< ::flexcraft_msgs::GetPcl >::value();
  }
  static const char* value(const ::flexcraft_msgs::GetPclResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::flexcraft_msgs::GetPclResponse> should match
// service_traits::DataType< ::flexcraft_msgs::GetPcl >
template<>
struct DataType< ::flexcraft_msgs::GetPclResponse>
{
  static const char* value()
  {
    return DataType< ::flexcraft_msgs::GetPcl >::value();
  }
  static const char* value(const ::flexcraft_msgs::GetPclResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // FLEXCRAFT_MSGS_MESSAGE_GETPCL_H
