// Generated by gencpp from file flexcraft_msgs/GetPclResponse.msg
// DO NOT EDIT!


#ifndef FLEXCRAFT_MSGS_MESSAGE_GETPCLRESPONSE_H
#define FLEXCRAFT_MSGS_MESSAGE_GETPCLRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point.h>

namespace flexcraft_msgs
{
template <class ContainerAllocator>
struct GetPclResponse_
{
  typedef GetPclResponse_<ContainerAllocator> Type;

  GetPclResponse_()
    : cloud()
    , success(false)  {
    }
  GetPclResponse_(const ContainerAllocator& _alloc)
    : cloud(_alloc)
    , success(false)  {
  (void)_alloc;
    }



   typedef std::vector< ::geometry_msgs::Point_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::geometry_msgs::Point_<ContainerAllocator> >> _cloud_type;
  _cloud_type cloud;

   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::flexcraft_msgs::GetPclResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::flexcraft_msgs::GetPclResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetPclResponse_

typedef ::flexcraft_msgs::GetPclResponse_<std::allocator<void> > GetPclResponse;

typedef boost::shared_ptr< ::flexcraft_msgs::GetPclResponse > GetPclResponsePtr;
typedef boost::shared_ptr< ::flexcraft_msgs::GetPclResponse const> GetPclResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::flexcraft_msgs::GetPclResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::flexcraft_msgs::GetPclResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::flexcraft_msgs::GetPclResponse_<ContainerAllocator1> & lhs, const ::flexcraft_msgs::GetPclResponse_<ContainerAllocator2> & rhs)
{
  return lhs.cloud == rhs.cloud &&
    lhs.success == rhs.success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::flexcraft_msgs::GetPclResponse_<ContainerAllocator1> & lhs, const ::flexcraft_msgs::GetPclResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace flexcraft_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::flexcraft_msgs::GetPclResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::flexcraft_msgs::GetPclResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::flexcraft_msgs::GetPclResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::flexcraft_msgs::GetPclResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::flexcraft_msgs::GetPclResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::flexcraft_msgs::GetPclResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::flexcraft_msgs::GetPclResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6675bded5f9acf2f2266e0dd468b6db0";
  }

  static const char* value(const ::flexcraft_msgs::GetPclResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6675bded5f9acf2fULL;
  static const uint64_t static_value2 = 0x2266e0dd468b6db0ULL;
};

template<class ContainerAllocator>
struct DataType< ::flexcraft_msgs::GetPclResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "flexcraft_msgs/GetPclResponse";
  }

  static const char* value(const ::flexcraft_msgs::GetPclResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::flexcraft_msgs::GetPclResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Point[] cloud\n"
"bool success\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::flexcraft_msgs::GetPclResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::flexcraft_msgs::GetPclResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.cloud);
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetPclResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::flexcraft_msgs::GetPclResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::flexcraft_msgs::GetPclResponse_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "cloud: ";
    if (v.cloud.empty() || false)
      s << "[";
    for (size_t i = 0; i < v.cloud.size(); ++i)
    {
      if (false && i > 0)
        s << ", ";
      else if (!false)
        s << std::endl << indent << "  -";
      Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, false ? std::string() : indent + "    ", v.cloud[i]);
    }
    if (v.cloud.empty() || false)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FLEXCRAFT_MSGS_MESSAGE_GETPCLRESPONSE_H
