// Generated by gencpp from file flexcraft_msgs/ResetOctomapRequest.msg
// DO NOT EDIT!


#ifndef FLEXCRAFT_MSGS_MESSAGE_RESETOCTOMAPREQUEST_H
#define FLEXCRAFT_MSGS_MESSAGE_RESETOCTOMAPREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace flexcraft_msgs
{
template <class ContainerAllocator>
struct ResetOctomapRequest_
{
  typedef ResetOctomapRequest_<ContainerAllocator> Type;

  ResetOctomapRequest_()
    {
    }
  ResetOctomapRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::flexcraft_msgs::ResetOctomapRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::flexcraft_msgs::ResetOctomapRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ResetOctomapRequest_

typedef ::flexcraft_msgs::ResetOctomapRequest_<std::allocator<void> > ResetOctomapRequest;

typedef boost::shared_ptr< ::flexcraft_msgs::ResetOctomapRequest > ResetOctomapRequestPtr;
typedef boost::shared_ptr< ::flexcraft_msgs::ResetOctomapRequest const> ResetOctomapRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::flexcraft_msgs::ResetOctomapRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::flexcraft_msgs::ResetOctomapRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace flexcraft_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::flexcraft_msgs::ResetOctomapRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::flexcraft_msgs::ResetOctomapRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::flexcraft_msgs::ResetOctomapRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::flexcraft_msgs::ResetOctomapRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::flexcraft_msgs::ResetOctomapRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::flexcraft_msgs::ResetOctomapRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::flexcraft_msgs::ResetOctomapRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::flexcraft_msgs::ResetOctomapRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::flexcraft_msgs::ResetOctomapRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "flexcraft_msgs/ResetOctomapRequest";
  }

  static const char* value(const ::flexcraft_msgs::ResetOctomapRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::flexcraft_msgs::ResetOctomapRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::flexcraft_msgs::ResetOctomapRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::flexcraft_msgs::ResetOctomapRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ResetOctomapRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::flexcraft_msgs::ResetOctomapRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::flexcraft_msgs::ResetOctomapRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // FLEXCRAFT_MSGS_MESSAGE_RESETOCTOMAPREQUEST_H
