// Generated by gencpp from file flexcraft_msgs/ResetOctomap.msg
// DO NOT EDIT!


#ifndef FLEXCRAFT_MSGS_MESSAGE_RESETOCTOMAP_H
#define FLEXCRAFT_MSGS_MESSAGE_RESETOCTOMAP_H

#include <ros/service_traits.h>


#include <flexcraft_msgs/ResetOctomapRequest.h>
#include <flexcraft_msgs/ResetOctomapResponse.h>


namespace flexcraft_msgs
{

struct ResetOctomap
{

typedef ResetOctomapRequest Request;
typedef ResetOctomapResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ResetOctomap
} // namespace flexcraft_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::flexcraft_msgs::ResetOctomap > {
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::flexcraft_msgs::ResetOctomap&) { return value(); }
};

template<>
struct DataType< ::flexcraft_msgs::ResetOctomap > {
  static const char* value()
  {
    return "flexcraft_msgs/ResetOctomap";
  }

  static const char* value(const ::flexcraft_msgs::ResetOctomap&) { return value(); }
};


// service_traits::MD5Sum< ::flexcraft_msgs::ResetOctomapRequest> should match
// service_traits::MD5Sum< ::flexcraft_msgs::ResetOctomap >
template<>
struct MD5Sum< ::flexcraft_msgs::ResetOctomapRequest>
{
  static const char* value()
  {
    return MD5Sum< ::flexcraft_msgs::ResetOctomap >::value();
  }
  static const char* value(const ::flexcraft_msgs::ResetOctomapRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::flexcraft_msgs::ResetOctomapRequest> should match
// service_traits::DataType< ::flexcraft_msgs::ResetOctomap >
template<>
struct DataType< ::flexcraft_msgs::ResetOctomapRequest>
{
  static const char* value()
  {
    return DataType< ::flexcraft_msgs::ResetOctomap >::value();
  }
  static const char* value(const ::flexcraft_msgs::ResetOctomapRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::flexcraft_msgs::ResetOctomapResponse> should match
// service_traits::MD5Sum< ::flexcraft_msgs::ResetOctomap >
template<>
struct MD5Sum< ::flexcraft_msgs::ResetOctomapResponse>
{
  static const char* value()
  {
    return MD5Sum< ::flexcraft_msgs::ResetOctomap >::value();
  }
  static const char* value(const ::flexcraft_msgs::ResetOctomapResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::flexcraft_msgs::ResetOctomapResponse> should match
// service_traits::DataType< ::flexcraft_msgs::ResetOctomap >
template<>
struct DataType< ::flexcraft_msgs::ResetOctomapResponse>
{
  static const char* value()
  {
    return DataType< ::flexcraft_msgs::ResetOctomap >::value();
  }
  static const char* value(const ::flexcraft_msgs::ResetOctomapResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // FLEXCRAFT_MSGS_MESSAGE_RESETOCTOMAP_H
