// Generated by gencpp from file flexcraft_msgs/SampleViewsResponse.msg
// DO NOT EDIT!


#ifndef FLEXCRAFT_MSGS_MESSAGE_SAMPLEVIEWSRESPONSE_H
#define FLEXCRAFT_MSGS_MESSAGE_SAMPLEVIEWSRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/PoseArray.h>

namespace flexcraft_msgs
{
template <class ContainerAllocator>
struct SampleViewsResponse_
{
  typedef SampleViewsResponse_<ContainerAllocator> Type;

  SampleViewsResponse_()
    : view_samples()  {
    }
  SampleViewsResponse_(const ContainerAllocator& _alloc)
    : view_samples(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::PoseArray_<ContainerAllocator>  _view_samples_type;
  _view_samples_type view_samples;





  typedef boost::shared_ptr< ::flexcraft_msgs::SampleViewsResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::flexcraft_msgs::SampleViewsResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SampleViewsResponse_

typedef ::flexcraft_msgs::SampleViewsResponse_<std::allocator<void> > SampleViewsResponse;

typedef boost::shared_ptr< ::flexcraft_msgs::SampleViewsResponse > SampleViewsResponsePtr;
typedef boost::shared_ptr< ::flexcraft_msgs::SampleViewsResponse const> SampleViewsResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::flexcraft_msgs::SampleViewsResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::flexcraft_msgs::SampleViewsResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::flexcraft_msgs::SampleViewsResponse_<ContainerAllocator1> & lhs, const ::flexcraft_msgs::SampleViewsResponse_<ContainerAllocator2> & rhs)
{
  return lhs.view_samples == rhs.view_samples;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::flexcraft_msgs::SampleViewsResponse_<ContainerAllocator1> & lhs, const ::flexcraft_msgs::SampleViewsResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace flexcraft_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::flexcraft_msgs::SampleViewsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::flexcraft_msgs::SampleViewsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::flexcraft_msgs::SampleViewsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::flexcraft_msgs::SampleViewsResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::flexcraft_msgs::SampleViewsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::flexcraft_msgs::SampleViewsResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::flexcraft_msgs::SampleViewsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "48ce1354a93a015dbf65797167028470";
  }

  static const char* value(const ::flexcraft_msgs::SampleViewsResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x48ce1354a93a015dULL;
  static const uint64_t static_value2 = 0xbf65797167028470ULL;
};

template<class ContainerAllocator>
struct DataType< ::flexcraft_msgs::SampleViewsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "flexcraft_msgs/SampleViewsResponse";
  }

  static const char* value(const ::flexcraft_msgs::SampleViewsResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::flexcraft_msgs::SampleViewsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/PoseArray view_samples\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/PoseArray\n"
"# An array of poses with a header for global reference.\n"
"\n"
"Header header\n"
"\n"
"Pose[] poses\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::flexcraft_msgs::SampleViewsResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::flexcraft_msgs::SampleViewsResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.view_samples);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SampleViewsResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::flexcraft_msgs::SampleViewsResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::flexcraft_msgs::SampleViewsResponse_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "view_samples: ";
    Printer< ::geometry_msgs::PoseArray_<ContainerAllocator> >::stream(s, indent + "  ", v.view_samples);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FLEXCRAFT_MSGS_MESSAGE_SAMPLEVIEWSRESPONSE_H
