// Generated by gencpp from file flexcraft_msgs/SampleViewsRequest.msg
// DO NOT EDIT!


#ifndef FLEXCRAFT_MSGS_MESSAGE_SAMPLEVIEWSREQUEST_H
#define FLEXCRAFT_MSGS_MESSAGE_SAMPLEVIEWSREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point.h>

namespace flexcraft_msgs
{
template <class ContainerAllocator>
struct SampleViewsRequest_
{
  typedef SampleViewsRequest_<ContainerAllocator> Type;

  SampleViewsRequest_()
    : sampler_type()
    , num_samples(0)
    , center()
    , radius(0.0)
    , length(0.0)
    , min_theta(0.0)
    , max_theta(0.0)
    , delta_yaw(0.0)
    , delta_pitch(0.0)  {
    }
  SampleViewsRequest_(const ContainerAllocator& _alloc)
    : sampler_type(_alloc)
    , num_samples(0)
    , center(_alloc)
    , radius(0.0)
    , length(0.0)
    , min_theta(0.0)
    , max_theta(0.0)
    , delta_yaw(0.0)
    , delta_pitch(0.0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _sampler_type_type;
  _sampler_type_type sampler_type;

   typedef int32_t _num_samples_type;
  _num_samples_type num_samples;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _center_type;
  _center_type center;

   typedef float _radius_type;
  _radius_type radius;

   typedef float _length_type;
  _length_type length;

   typedef float _min_theta_type;
  _min_theta_type min_theta;

   typedef float _max_theta_type;
  _max_theta_type max_theta;

   typedef float _delta_yaw_type;
  _delta_yaw_type delta_yaw;

   typedef float _delta_pitch_type;
  _delta_pitch_type delta_pitch;





  typedef boost::shared_ptr< ::flexcraft_msgs::SampleViewsRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::flexcraft_msgs::SampleViewsRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SampleViewsRequest_

typedef ::flexcraft_msgs::SampleViewsRequest_<std::allocator<void> > SampleViewsRequest;

typedef boost::shared_ptr< ::flexcraft_msgs::SampleViewsRequest > SampleViewsRequestPtr;
typedef boost::shared_ptr< ::flexcraft_msgs::SampleViewsRequest const> SampleViewsRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::flexcraft_msgs::SampleViewsRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::flexcraft_msgs::SampleViewsRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::flexcraft_msgs::SampleViewsRequest_<ContainerAllocator1> & lhs, const ::flexcraft_msgs::SampleViewsRequest_<ContainerAllocator2> & rhs)
{
  return lhs.sampler_type == rhs.sampler_type &&
    lhs.num_samples == rhs.num_samples &&
    lhs.center == rhs.center &&
    lhs.radius == rhs.radius &&
    lhs.length == rhs.length &&
    lhs.min_theta == rhs.min_theta &&
    lhs.max_theta == rhs.max_theta &&
    lhs.delta_yaw == rhs.delta_yaw &&
    lhs.delta_pitch == rhs.delta_pitch;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::flexcraft_msgs::SampleViewsRequest_<ContainerAllocator1> & lhs, const ::flexcraft_msgs::SampleViewsRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace flexcraft_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::flexcraft_msgs::SampleViewsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::flexcraft_msgs::SampleViewsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::flexcraft_msgs::SampleViewsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::flexcraft_msgs::SampleViewsRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::flexcraft_msgs::SampleViewsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::flexcraft_msgs::SampleViewsRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::flexcraft_msgs::SampleViewsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "223853558c0f335c5cf1ea3952fb2976";
  }

  static const char* value(const ::flexcraft_msgs::SampleViewsRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x223853558c0f335cULL;
  static const uint64_t static_value2 = 0x5cf1ea3952fb2976ULL;
};

template<class ContainerAllocator>
struct DataType< ::flexcraft_msgs::SampleViewsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "flexcraft_msgs/SampleViewsRequest";
  }

  static const char* value(const ::flexcraft_msgs::SampleViewsRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::flexcraft_msgs::SampleViewsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string sampler_type\n"
"int32 num_samples\n"
"geometry_msgs/Point center\n"
"float32 radius\n"
"float32 length\n"
"float32 min_theta\n"
"float32 max_theta\n"
"float32 delta_yaw\n"
"float32 delta_pitch\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::flexcraft_msgs::SampleViewsRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::flexcraft_msgs::SampleViewsRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.sampler_type);
      stream.next(m.num_samples);
      stream.next(m.center);
      stream.next(m.radius);
      stream.next(m.length);
      stream.next(m.min_theta);
      stream.next(m.max_theta);
      stream.next(m.delta_yaw);
      stream.next(m.delta_pitch);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SampleViewsRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::flexcraft_msgs::SampleViewsRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::flexcraft_msgs::SampleViewsRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "sampler_type: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.sampler_type);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "num_samples: ";
    Printer<int32_t>::stream(s, indent + "  ", v.num_samples);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "center: ";
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.center);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "radius: ";
    Printer<float>::stream(s, indent + "  ", v.radius);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "length: ";
    Printer<float>::stream(s, indent + "  ", v.length);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "min_theta: ";
    Printer<float>::stream(s, indent + "  ", v.min_theta);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "max_theta: ";
    Printer<float>::stream(s, indent + "  ", v.max_theta);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "delta_yaw: ";
    Printer<float>::stream(s, indent + "  ", v.delta_yaw);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "delta_pitch: ";
    Printer<float>::stream(s, indent + "  ", v.delta_pitch);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FLEXCRAFT_MSGS_MESSAGE_SAMPLEVIEWSREQUEST_H
