// Generated by gencpp from file flexcraft_msgs/SampleViews.msg
// DO NOT EDIT!


#ifndef FLEXCRAFT_MSGS_MESSAGE_SAMPLEVIEWS_H
#define FLEXCRAFT_MSGS_MESSAGE_SAMPLEVIEWS_H

#include <ros/service_traits.h>


#include <flexcraft_msgs/SampleViewsRequest.h>
#include <flexcraft_msgs/SampleViewsResponse.h>


namespace flexcraft_msgs
{

struct SampleViews
{

typedef SampleViewsRequest Request;
typedef SampleViewsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SampleViews
} // namespace flexcraft_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::flexcraft_msgs::SampleViews > {
  static const char* value()
  {
    return "b67eb928b26db8cb27e2c57ed968be8b";
  }

  static const char* value(const ::flexcraft_msgs::SampleViews&) { return value(); }
};

template<>
struct DataType< ::flexcraft_msgs::SampleViews > {
  static const char* value()
  {
    return "flexcraft_msgs/SampleViews";
  }

  static const char* value(const ::flexcraft_msgs::SampleViews&) { return value(); }
};


// service_traits::MD5Sum< ::flexcraft_msgs::SampleViewsRequest> should match
// service_traits::MD5Sum< ::flexcraft_msgs::SampleViews >
template<>
struct MD5Sum< ::flexcraft_msgs::SampleViewsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::flexcraft_msgs::SampleViews >::value();
  }
  static const char* value(const ::flexcraft_msgs::SampleViewsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::flexcraft_msgs::SampleViewsRequest> should match
// service_traits::DataType< ::flexcraft_msgs::SampleViews >
template<>
struct DataType< ::flexcraft_msgs::SampleViewsRequest>
{
  static const char* value()
  {
    return DataType< ::flexcraft_msgs::SampleViews >::value();
  }
  static const char* value(const ::flexcraft_msgs::SampleViewsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::flexcraft_msgs::SampleViewsResponse> should match
// service_traits::MD5Sum< ::flexcraft_msgs::SampleViews >
template<>
struct MD5Sum< ::flexcraft_msgs::SampleViewsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::flexcraft_msgs::SampleViews >::value();
  }
  static const char* value(const ::flexcraft_msgs::SampleViewsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::flexcraft_msgs::SampleViewsResponse> should match
// service_traits::DataType< ::flexcraft_msgs::SampleViews >
template<>
struct DataType< ::flexcraft_msgs::SampleViewsResponse>
{
  static const char* value()
  {
    return DataType< ::flexcraft_msgs::SampleViews >::value();
  }
  static const char* value(const ::flexcraft_msgs::SampleViewsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // FLEXCRAFT_MSGS_MESSAGE_SAMPLEVIEWS_H
