// Generated by gencpp from file flexcraft_msgs/SaveOctomap.msg
// DO NOT EDIT!


#ifndef FLEXCRAFT_MSGS_MESSAGE_SAVEOCTOMAP_H
#define FLEXCRAFT_MSGS_MESSAGE_SAVEOCTOMAP_H

#include <ros/service_traits.h>


#include <flexcraft_msgs/SaveOctomapRequest.h>
#include <flexcraft_msgs/SaveOctomapResponse.h>


namespace flexcraft_msgs
{

struct SaveOctomap
{

typedef SaveOctomapRequest Request;
typedef SaveOctomapResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SaveOctomap
} // namespace flexcraft_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::flexcraft_msgs::SaveOctomap > {
  static const char* value()
  {
    return "ac658a90398538172f073c94f749576e";
  }

  static const char* value(const ::flexcraft_msgs::SaveOctomap&) { return value(); }
};

template<>
struct DataType< ::flexcraft_msgs::SaveOctomap > {
  static const char* value()
  {
    return "flexcraft_msgs/SaveOctomap";
  }

  static const char* value(const ::flexcraft_msgs::SaveOctomap&) { return value(); }
};


// service_traits::MD5Sum< ::flexcraft_msgs::SaveOctomapRequest> should match
// service_traits::MD5Sum< ::flexcraft_msgs::SaveOctomap >
template<>
struct MD5Sum< ::flexcraft_msgs::SaveOctomapRequest>
{
  static const char* value()
  {
    return MD5Sum< ::flexcraft_msgs::SaveOctomap >::value();
  }
  static const char* value(const ::flexcraft_msgs::SaveOctomapRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::flexcraft_msgs::SaveOctomapRequest> should match
// service_traits::DataType< ::flexcraft_msgs::SaveOctomap >
template<>
struct DataType< ::flexcraft_msgs::SaveOctomapRequest>
{
  static const char* value()
  {
    return DataType< ::flexcraft_msgs::SaveOctomap >::value();
  }
  static const char* value(const ::flexcraft_msgs::SaveOctomapRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::flexcraft_msgs::SaveOctomapResponse> should match
// service_traits::MD5Sum< ::flexcraft_msgs::SaveOctomap >
template<>
struct MD5Sum< ::flexcraft_msgs::SaveOctomapResponse>
{
  static const char* value()
  {
    return MD5Sum< ::flexcraft_msgs::SaveOctomap >::value();
  }
  static const char* value(const ::flexcraft_msgs::SaveOctomapResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::flexcraft_msgs::SaveOctomapResponse> should match
// service_traits::DataType< ::flexcraft_msgs::SaveOctomap >
template<>
struct DataType< ::flexcraft_msgs::SaveOctomapResponse>
{
  static const char* value()
  {
    return DataType< ::flexcraft_msgs::SaveOctomap >::value();
  }
  static const char* value(const ::flexcraft_msgs::SaveOctomapResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // FLEXCRAFT_MSGS_MESSAGE_SAVEOCTOMAP_H
