// Generated by gencpp from file flexcraft_msgs/SaveOctomapResponse.msg
// DO NOT EDIT!


#ifndef FLEXCRAFT_MSGS_MESSAGE_SAVEOCTOMAPRESPONSE_H
#define FLEXCRAFT_MSGS_MESSAGE_SAVEOCTOMAPRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace flexcraft_msgs
{
template <class ContainerAllocator>
struct SaveOctomapResponse_
{
  typedef SaveOctomapResponse_<ContainerAllocator> Type;

  SaveOctomapResponse_()
    : success(false)  {
    }
  SaveOctomapResponse_(const ContainerAllocator& _alloc)
    : success(false)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::flexcraft_msgs::SaveOctomapResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::flexcraft_msgs::SaveOctomapResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SaveOctomapResponse_

typedef ::flexcraft_msgs::SaveOctomapResponse_<std::allocator<void> > SaveOctomapResponse;

typedef boost::shared_ptr< ::flexcraft_msgs::SaveOctomapResponse > SaveOctomapResponsePtr;
typedef boost::shared_ptr< ::flexcraft_msgs::SaveOctomapResponse const> SaveOctomapResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::flexcraft_msgs::SaveOctomapResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::flexcraft_msgs::SaveOctomapResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::flexcraft_msgs::SaveOctomapResponse_<ContainerAllocator1> & lhs, const ::flexcraft_msgs::SaveOctomapResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::flexcraft_msgs::SaveOctomapResponse_<ContainerAllocator1> & lhs, const ::flexcraft_msgs::SaveOctomapResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace flexcraft_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::flexcraft_msgs::SaveOctomapResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::flexcraft_msgs::SaveOctomapResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::flexcraft_msgs::SaveOctomapResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::flexcraft_msgs::SaveOctomapResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::flexcraft_msgs::SaveOctomapResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::flexcraft_msgs::SaveOctomapResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::flexcraft_msgs::SaveOctomapResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::flexcraft_msgs::SaveOctomapResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x358e233cde0c8a8bULL;
  static const uint64_t static_value2 = 0xcfea4ce193f8fc15ULL;
};

template<class ContainerAllocator>
struct DataType< ::flexcraft_msgs::SaveOctomapResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "flexcraft_msgs/SaveOctomapResponse";
  }

  static const char* value(const ::flexcraft_msgs::SaveOctomapResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::flexcraft_msgs::SaveOctomapResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n"
;
  }

  static const char* value(const ::flexcraft_msgs::SaveOctomapResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::flexcraft_msgs::SaveOctomapResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SaveOctomapResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::flexcraft_msgs::SaveOctomapResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::flexcraft_msgs::SaveOctomapResponse_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FLEXCRAFT_MSGS_MESSAGE_SAVEOCTOMAPRESPONSE_H
