// Generated by gencpp from file flexcraft_msgs/SaveOctomapRequest.msg
// DO NOT EDIT!


#ifndef FLEXCRAFT_MSGS_MESSAGE_SAVEOCTOMAPREQUEST_H
#define FLEXCRAFT_MSGS_MESSAGE_SAVEOCTOMAPREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace flexcraft_msgs
{
template <class ContainerAllocator>
struct SaveOctomapRequest_
{
  typedef SaveOctomapRequest_<ContainerAllocator> Type;

  SaveOctomapRequest_()
    : file_path()
    , step(0)  {
    }
  SaveOctomapRequest_(const ContainerAllocator& _alloc)
    : file_path(_alloc)
    , step(0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _file_path_type;
  _file_path_type file_path;

   typedef int32_t _step_type;
  _step_type step;





  typedef boost::shared_ptr< ::flexcraft_msgs::SaveOctomapRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::flexcraft_msgs::SaveOctomapRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SaveOctomapRequest_

typedef ::flexcraft_msgs::SaveOctomapRequest_<std::allocator<void> > SaveOctomapRequest;

typedef boost::shared_ptr< ::flexcraft_msgs::SaveOctomapRequest > SaveOctomapRequestPtr;
typedef boost::shared_ptr< ::flexcraft_msgs::SaveOctomapRequest const> SaveOctomapRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::flexcraft_msgs::SaveOctomapRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::flexcraft_msgs::SaveOctomapRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::flexcraft_msgs::SaveOctomapRequest_<ContainerAllocator1> & lhs, const ::flexcraft_msgs::SaveOctomapRequest_<ContainerAllocator2> & rhs)
{
  return lhs.file_path == rhs.file_path &&
    lhs.step == rhs.step;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::flexcraft_msgs::SaveOctomapRequest_<ContainerAllocator1> & lhs, const ::flexcraft_msgs::SaveOctomapRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace flexcraft_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::flexcraft_msgs::SaveOctomapRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::flexcraft_msgs::SaveOctomapRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::flexcraft_msgs::SaveOctomapRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::flexcraft_msgs::SaveOctomapRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::flexcraft_msgs::SaveOctomapRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::flexcraft_msgs::SaveOctomapRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::flexcraft_msgs::SaveOctomapRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fde17d7bcc4299dce9719008c3b15dcf";
  }

  static const char* value(const ::flexcraft_msgs::SaveOctomapRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xfde17d7bcc4299dcULL;
  static const uint64_t static_value2 = 0xe9719008c3b15dcfULL;
};

template<class ContainerAllocator>
struct DataType< ::flexcraft_msgs::SaveOctomapRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "flexcraft_msgs/SaveOctomapRequest";
  }

  static const char* value(const ::flexcraft_msgs::SaveOctomapRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::flexcraft_msgs::SaveOctomapRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string file_path\n"
"int32 step\n"
;
  }

  static const char* value(const ::flexcraft_msgs::SaveOctomapRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::flexcraft_msgs::SaveOctomapRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.file_path);
      stream.next(m.step);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SaveOctomapRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::flexcraft_msgs::SaveOctomapRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::flexcraft_msgs::SaveOctomapRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "file_path: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.file_path);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "step: ";
    Printer<int32_t>::stream(s, indent + "  ", v.step);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FLEXCRAFT_MSGS_MESSAGE_SAVEOCTOMAPREQUEST_H
