// Generated by gencpp from file flexcraft_msgs/SemiCylinder.msg
// DO NOT EDIT!


#ifndef FLEXCRAFT_MSGS_MESSAGE_SEMICYLINDER_H
#define FLEXCRAFT_MSGS_MESSAGE_SEMICYLINDER_H

#include <ros/service_traits.h>


#include <flexcraft_msgs/SemiCylinderRequest.h>
#include <flexcraft_msgs/SemiCylinderResponse.h>


namespace flexcraft_msgs
{

struct SemiCylinder
{

typedef SemiCylinderRequest Request;
typedef SemiCylinderResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SemiCylinder
} // namespace flexcraft_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::flexcraft_msgs::SemiCylinder > {
  static const char* value()
  {
    return "f53643562a419117971ff923d0858358";
  }

  static const char* value(const ::flexcraft_msgs::SemiCylinder&) { return value(); }
};

template<>
struct DataType< ::flexcraft_msgs::SemiCylinder > {
  static const char* value()
  {
    return "flexcraft_msgs/SemiCylinder";
  }

  static const char* value(const ::flexcraft_msgs::SemiCylinder&) { return value(); }
};


// service_traits::MD5Sum< ::flexcraft_msgs::SemiCylinderRequest> should match
// service_traits::MD5Sum< ::flexcraft_msgs::SemiCylinder >
template<>
struct MD5Sum< ::flexcraft_msgs::SemiCylinderRequest>
{
  static const char* value()
  {
    return MD5Sum< ::flexcraft_msgs::SemiCylinder >::value();
  }
  static const char* value(const ::flexcraft_msgs::SemiCylinderRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::flexcraft_msgs::SemiCylinderRequest> should match
// service_traits::DataType< ::flexcraft_msgs::SemiCylinder >
template<>
struct DataType< ::flexcraft_msgs::SemiCylinderRequest>
{
  static const char* value()
  {
    return DataType< ::flexcraft_msgs::SemiCylinder >::value();
  }
  static const char* value(const ::flexcraft_msgs::SemiCylinderRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::flexcraft_msgs::SemiCylinderResponse> should match
// service_traits::MD5Sum< ::flexcraft_msgs::SemiCylinder >
template<>
struct MD5Sum< ::flexcraft_msgs::SemiCylinderResponse>
{
  static const char* value()
  {
    return MD5Sum< ::flexcraft_msgs::SemiCylinder >::value();
  }
  static const char* value(const ::flexcraft_msgs::SemiCylinderResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::flexcraft_msgs::SemiCylinderResponse> should match
// service_traits::DataType< ::flexcraft_msgs::SemiCylinder >
template<>
struct DataType< ::flexcraft_msgs::SemiCylinderResponse>
{
  static const char* value()
  {
    return DataType< ::flexcraft_msgs::SemiCylinder >::value();
  }
  static const char* value(const ::flexcraft_msgs::SemiCylinderResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // FLEXCRAFT_MSGS_MESSAGE_SEMICYLINDER_H
