# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from flexcraft_msgs/ComputeNBVRequest.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg
import std_msgs.msg

class ComputeNBVRequest(genpy.Message):
  _md5sum = "bbfb37c94fd0934978627014d83729ec"
  _type = "flexcraft_msgs/ComputeNBVRequest"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """geometry_msgs/PoseArray candidates
geometry_msgs/Point[] bbx_centers
geometry_msgs/Point[] bbx_sizes
int32 class_id

================================================================================
MSG: geometry_msgs/PoseArray
# An array of poses with a header for global reference.

Header header

Pose[] poses

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id

================================================================================
MSG: geometry_msgs/Pose
# A representation of pose in free space, composed of position and orientation. 
Point position
Quaternion orientation

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z

================================================================================
MSG: geometry_msgs/Quaternion
# This represents an orientation in free space in quaternion form.

float64 x
float64 y
float64 z
float64 w
"""
  __slots__ = ['candidates','bbx_centers','bbx_sizes','class_id']
  _slot_types = ['geometry_msgs/PoseArray','geometry_msgs/Point[]','geometry_msgs/Point[]','int32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       candidates,bbx_centers,bbx_sizes,class_id

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(ComputeNBVRequest, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.candidates is None:
        self.candidates = geometry_msgs.msg.PoseArray()
      if self.bbx_centers is None:
        self.bbx_centers = []
      if self.bbx_sizes is None:
        self.bbx_sizes = []
      if self.class_id is None:
        self.class_id = 0
    else:
      self.candidates = geometry_msgs.msg.PoseArray()
      self.bbx_centers = []
      self.bbx_sizes = []
      self.class_id = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.candidates.header.seq, _x.candidates.header.stamp.secs, _x.candidates.header.stamp.nsecs))
      _x = self.candidates.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      length = len(self.candidates.poses)
      buff.write(_struct_I.pack(length))
      for val1 in self.candidates.poses:
        _v1 = val1.position
        _x = _v1
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
        _v2 = val1.orientation
        _x = _v2
        buff.write(_get_struct_4d().pack(_x.x, _x.y, _x.z, _x.w))
      length = len(self.bbx_centers)
      buff.write(_struct_I.pack(length))
      for val1 in self.bbx_centers:
        _x = val1
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
      length = len(self.bbx_sizes)
      buff.write(_struct_I.pack(length))
      for val1 in self.bbx_sizes:
        _x = val1
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
      _x = self.class_id
      buff.write(_get_struct_i().pack(_x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.candidates is None:
        self.candidates = geometry_msgs.msg.PoseArray()
      if self.bbx_centers is None:
        self.bbx_centers = None
      if self.bbx_sizes is None:
        self.bbx_sizes = None
      end = 0
      _x = self
      start = end
      end += 12
      (_x.candidates.header.seq, _x.candidates.header.stamp.secs, _x.candidates.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.candidates.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.candidates.header.frame_id = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.candidates.poses = []
      for i in range(0, length):
        val1 = geometry_msgs.msg.Pose()
        _v3 = val1.position
        _x = _v3
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        _v4 = val1.orientation
        _x = _v4
        start = end
        end += 32
        (_x.x, _x.y, _x.z, _x.w,) = _get_struct_4d().unpack(str[start:end])
        self.candidates.poses.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.bbx_centers = []
      for i in range(0, length):
        val1 = geometry_msgs.msg.Point()
        _x = val1
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        self.bbx_centers.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.bbx_sizes = []
      for i in range(0, length):
        val1 = geometry_msgs.msg.Point()
        _x = val1
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        self.bbx_sizes.append(val1)
      start = end
      end += 4
      (self.class_id,) = _get_struct_i().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.candidates.header.seq, _x.candidates.header.stamp.secs, _x.candidates.header.stamp.nsecs))
      _x = self.candidates.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      length = len(self.candidates.poses)
      buff.write(_struct_I.pack(length))
      for val1 in self.candidates.poses:
        _v5 = val1.position
        _x = _v5
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
        _v6 = val1.orientation
        _x = _v6
        buff.write(_get_struct_4d().pack(_x.x, _x.y, _x.z, _x.w))
      length = len(self.bbx_centers)
      buff.write(_struct_I.pack(length))
      for val1 in self.bbx_centers:
        _x = val1
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
      length = len(self.bbx_sizes)
      buff.write(_struct_I.pack(length))
      for val1 in self.bbx_sizes:
        _x = val1
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
      _x = self.class_id
      buff.write(_get_struct_i().pack(_x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.candidates is None:
        self.candidates = geometry_msgs.msg.PoseArray()
      if self.bbx_centers is None:
        self.bbx_centers = None
      if self.bbx_sizes is None:
        self.bbx_sizes = None
      end = 0
      _x = self
      start = end
      end += 12
      (_x.candidates.header.seq, _x.candidates.header.stamp.secs, _x.candidates.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.candidates.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.candidates.header.frame_id = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.candidates.poses = []
      for i in range(0, length):
        val1 = geometry_msgs.msg.Pose()
        _v7 = val1.position
        _x = _v7
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        _v8 = val1.orientation
        _x = _v8
        start = end
        end += 32
        (_x.x, _x.y, _x.z, _x.w,) = _get_struct_4d().unpack(str[start:end])
        self.candidates.poses.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.bbx_centers = []
      for i in range(0, length):
        val1 = geometry_msgs.msg.Point()
        _x = val1
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        self.bbx_centers.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.bbx_sizes = []
      for i in range(0, length):
        val1 = geometry_msgs.msg.Point()
        _x = val1
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        self.bbx_sizes.append(val1)
      start = end
      end += 4
      (self.class_id,) = _get_struct_i().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_3d = None
def _get_struct_3d():
    global _struct_3d
    if _struct_3d is None:
        _struct_3d = struct.Struct("<3d")
    return _struct_3d
_struct_4d = None
def _get_struct_4d():
    global _struct_4d
    if _struct_4d is None:
        _struct_4d = struct.Struct("<4d")
    return _struct_4d
_struct_i = None
def _get_struct_i():
    global _struct_i
    if _struct_i is None:
        _struct_i = struct.Struct("<i")
    return _struct_i
# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from flexcraft_msgs/ComputeNBVResponse.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg

class ComputeNBVResponse(genpy.Message):
  _md5sum = "feeb8d2b0d0525de437e3fe9d317f4c5"
  _type = "flexcraft_msgs/ComputeNBVResponse"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """geometry_msgs/Pose nbv_pose
int32 nbv_index
bool success

================================================================================
MSG: geometry_msgs/Pose
# A representation of pose in free space, composed of position and orientation. 
Point position
Quaternion orientation

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z

================================================================================
MSG: geometry_msgs/Quaternion
# This represents an orientation in free space in quaternion form.

float64 x
float64 y
float64 z
float64 w
"""
  __slots__ = ['nbv_pose','nbv_index','success']
  _slot_types = ['geometry_msgs/Pose','int32','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       nbv_pose,nbv_index,success

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(ComputeNBVResponse, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.nbv_pose is None:
        self.nbv_pose = geometry_msgs.msg.Pose()
      if self.nbv_index is None:
        self.nbv_index = 0
      if self.success is None:
        self.success = False
    else:
      self.nbv_pose = geometry_msgs.msg.Pose()
      self.nbv_index = 0
      self.success = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_7diB().pack(_x.nbv_pose.position.x, _x.nbv_pose.position.y, _x.nbv_pose.position.z, _x.nbv_pose.orientation.x, _x.nbv_pose.orientation.y, _x.nbv_pose.orientation.z, _x.nbv_pose.orientation.w, _x.nbv_index, _x.success))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.nbv_pose is None:
        self.nbv_pose = geometry_msgs.msg.Pose()
      end = 0
      _x = self
      start = end
      end += 61
      (_x.nbv_pose.position.x, _x.nbv_pose.position.y, _x.nbv_pose.position.z, _x.nbv_pose.orientation.x, _x.nbv_pose.orientation.y, _x.nbv_pose.orientation.z, _x.nbv_pose.orientation.w, _x.nbv_index, _x.success,) = _get_struct_7diB().unpack(str[start:end])
      self.success = bool(self.success)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_7diB().pack(_x.nbv_pose.position.x, _x.nbv_pose.position.y, _x.nbv_pose.position.z, _x.nbv_pose.orientation.x, _x.nbv_pose.orientation.y, _x.nbv_pose.orientation.z, _x.nbv_pose.orientation.w, _x.nbv_index, _x.success))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.nbv_pose is None:
        self.nbv_pose = geometry_msgs.msg.Pose()
      end = 0
      _x = self
      start = end
      end += 61
      (_x.nbv_pose.position.x, _x.nbv_pose.position.y, _x.nbv_pose.position.z, _x.nbv_pose.orientation.x, _x.nbv_pose.orientation.y, _x.nbv_pose.orientation.z, _x.nbv_pose.orientation.w, _x.nbv_index, _x.success,) = _get_struct_7diB().unpack(str[start:end])
      self.success = bool(self.success)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_7diB = None
def _get_struct_7diB():
    global _struct_7diB
    if _struct_7diB is None:
        _struct_7diB = struct.Struct("<7diB")
    return _struct_7diB
class ComputeNBV(object):
  _type          = 'flexcraft_msgs/ComputeNBV'
  _md5sum = 'ce14f1e75e40af74df5ebd698c79385b'
  _request_class  = ComputeNBVRequest
  _response_class = ComputeNBVResponse
