# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from flexcraft_msgs/SampleViewsRequest.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg

class SampleViewsRequest(genpy.Message):
  _md5sum = "223853558c0f335c5cf1ea3952fb2976"
  _type = "flexcraft_msgs/SampleViewsRequest"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """string sampler_type
int32 num_samples
geometry_msgs/Point center
float32 radius
float32 length
float32 min_theta
float32 max_theta
float32 delta_yaw
float32 delta_pitch

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z
"""
  __slots__ = ['sampler_type','num_samples','center','radius','length','min_theta','max_theta','delta_yaw','delta_pitch']
  _slot_types = ['string','int32','geometry_msgs/Point','float32','float32','float32','float32','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       sampler_type,num_samples,center,radius,length,min_theta,max_theta,delta_yaw,delta_pitch

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(SampleViewsRequest, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.sampler_type is None:
        self.sampler_type = ''
      if self.num_samples is None:
        self.num_samples = 0
      if self.center is None:
        self.center = geometry_msgs.msg.Point()
      if self.radius is None:
        self.radius = 0.
      if self.length is None:
        self.length = 0.
      if self.min_theta is None:
        self.min_theta = 0.
      if self.max_theta is None:
        self.max_theta = 0.
      if self.delta_yaw is None:
        self.delta_yaw = 0.
      if self.delta_pitch is None:
        self.delta_pitch = 0.
    else:
      self.sampler_type = ''
      self.num_samples = 0
      self.center = geometry_msgs.msg.Point()
      self.radius = 0.
      self.length = 0.
      self.min_theta = 0.
      self.max_theta = 0.
      self.delta_yaw = 0.
      self.delta_pitch = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self.sampler_type
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_i3d6f().pack(_x.num_samples, _x.center.x, _x.center.y, _x.center.z, _x.radius, _x.length, _x.min_theta, _x.max_theta, _x.delta_yaw, _x.delta_pitch))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.center is None:
        self.center = geometry_msgs.msg.Point()
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.sampler_type = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.sampler_type = str[start:end]
      _x = self
      start = end
      end += 52
      (_x.num_samples, _x.center.x, _x.center.y, _x.center.z, _x.radius, _x.length, _x.min_theta, _x.max_theta, _x.delta_yaw, _x.delta_pitch,) = _get_struct_i3d6f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self.sampler_type
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_i3d6f().pack(_x.num_samples, _x.center.x, _x.center.y, _x.center.z, _x.radius, _x.length, _x.min_theta, _x.max_theta, _x.delta_yaw, _x.delta_pitch))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.center is None:
        self.center = geometry_msgs.msg.Point()
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.sampler_type = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.sampler_type = str[start:end]
      _x = self
      start = end
      end += 52
      (_x.num_samples, _x.center.x, _x.center.y, _x.center.z, _x.radius, _x.length, _x.min_theta, _x.max_theta, _x.delta_yaw, _x.delta_pitch,) = _get_struct_i3d6f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_i3d6f = None
def _get_struct_i3d6f():
    global _struct_i3d6f
    if _struct_i3d6f is None:
        _struct_i3d6f = struct.Struct("<i3d6f")
    return _struct_i3d6f
# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from flexcraft_msgs/SampleViewsResponse.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg
import std_msgs.msg

class SampleViewsResponse(genpy.Message):
  _md5sum = "48ce1354a93a015dbf65797167028470"
  _type = "flexcraft_msgs/SampleViewsResponse"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """geometry_msgs/PoseArray view_samples

================================================================================
MSG: geometry_msgs/PoseArray
# An array of poses with a header for global reference.

Header header

Pose[] poses

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id

================================================================================
MSG: geometry_msgs/Pose
# A representation of pose in free space, composed of position and orientation. 
Point position
Quaternion orientation

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z

================================================================================
MSG: geometry_msgs/Quaternion
# This represents an orientation in free space in quaternion form.

float64 x
float64 y
float64 z
float64 w
"""
  __slots__ = ['view_samples']
  _slot_types = ['geometry_msgs/PoseArray']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       view_samples

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(SampleViewsResponse, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.view_samples is None:
        self.view_samples = geometry_msgs.msg.PoseArray()
    else:
      self.view_samples = geometry_msgs.msg.PoseArray()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.view_samples.header.seq, _x.view_samples.header.stamp.secs, _x.view_samples.header.stamp.nsecs))
      _x = self.view_samples.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      length = len(self.view_samples.poses)
      buff.write(_struct_I.pack(length))
      for val1 in self.view_samples.poses:
        _v1 = val1.position
        _x = _v1
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
        _v2 = val1.orientation
        _x = _v2
        buff.write(_get_struct_4d().pack(_x.x, _x.y, _x.z, _x.w))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.view_samples is None:
        self.view_samples = geometry_msgs.msg.PoseArray()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.view_samples.header.seq, _x.view_samples.header.stamp.secs, _x.view_samples.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.view_samples.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.view_samples.header.frame_id = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.view_samples.poses = []
      for i in range(0, length):
        val1 = geometry_msgs.msg.Pose()
        _v3 = val1.position
        _x = _v3
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        _v4 = val1.orientation
        _x = _v4
        start = end
        end += 32
        (_x.x, _x.y, _x.z, _x.w,) = _get_struct_4d().unpack(str[start:end])
        self.view_samples.poses.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.view_samples.header.seq, _x.view_samples.header.stamp.secs, _x.view_samples.header.stamp.nsecs))
      _x = self.view_samples.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      length = len(self.view_samples.poses)
      buff.write(_struct_I.pack(length))
      for val1 in self.view_samples.poses:
        _v5 = val1.position
        _x = _v5
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
        _v6 = val1.orientation
        _x = _v6
        buff.write(_get_struct_4d().pack(_x.x, _x.y, _x.z, _x.w))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.view_samples is None:
        self.view_samples = geometry_msgs.msg.PoseArray()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.view_samples.header.seq, _x.view_samples.header.stamp.secs, _x.view_samples.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.view_samples.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.view_samples.header.frame_id = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.view_samples.poses = []
      for i in range(0, length):
        val1 = geometry_msgs.msg.Pose()
        _v7 = val1.position
        _x = _v7
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        _v8 = val1.orientation
        _x = _v8
        start = end
        end += 32
        (_x.x, _x.y, _x.z, _x.w,) = _get_struct_4d().unpack(str[start:end])
        self.view_samples.poses.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_3d = None
def _get_struct_3d():
    global _struct_3d
    if _struct_3d is None:
        _struct_3d = struct.Struct("<3d")
    return _struct_3d
_struct_4d = None
def _get_struct_4d():
    global _struct_4d
    if _struct_4d is None:
        _struct_4d = struct.Struct("<4d")
    return _struct_4d
class SampleViews(object):
  _type          = 'flexcraft_msgs/SampleViews'
  _md5sum = 'b67eb928b26db8cb27e2c57ed968be8b'
  _request_class  = SampleViewsRequest
  _response_class = SampleViewsResponse
