// Generated by gencpp from file ur_msgs/GetRobotSoftwareVersion.msg
// DO NOT EDIT!


#ifndef UR_MSGS_MESSAGE_GETROBOTSOFTWAREVERSION_H
#define UR_MSGS_MESSAGE_GETROBOTSOFTWAREVERSION_H

#include <ros/service_traits.h>


#include <ur_msgs/GetRobotSoftwareVersionRequest.h>
#include <ur_msgs/GetRobotSoftwareVersionResponse.h>


namespace ur_msgs
{

struct GetRobotSoftwareVersion
{

typedef GetRobotSoftwareVersionRequest Request;
typedef GetRobotSoftwareVersionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetRobotSoftwareVersion
} // namespace ur_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ur_msgs::GetRobotSoftwareVersion > {
  static const char* value()
  {
    return "eea0f1664f7955042558cb2bf2c766ad";
  }

  static const char* value(const ::ur_msgs::GetRobotSoftwareVersion&) { return value(); }
};

template<>
struct DataType< ::ur_msgs::GetRobotSoftwareVersion > {
  static const char* value()
  {
    return "ur_msgs/GetRobotSoftwareVersion";
  }

  static const char* value(const ::ur_msgs::GetRobotSoftwareVersion&) { return value(); }
};


// service_traits::MD5Sum< ::ur_msgs::GetRobotSoftwareVersionRequest> should match
// service_traits::MD5Sum< ::ur_msgs::GetRobotSoftwareVersion >
template<>
struct MD5Sum< ::ur_msgs::GetRobotSoftwareVersionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ur_msgs::GetRobotSoftwareVersion >::value();
  }
  static const char* value(const ::ur_msgs::GetRobotSoftwareVersionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ur_msgs::GetRobotSoftwareVersionRequest> should match
// service_traits::DataType< ::ur_msgs::GetRobotSoftwareVersion >
template<>
struct DataType< ::ur_msgs::GetRobotSoftwareVersionRequest>
{
  static const char* value()
  {
    return DataType< ::ur_msgs::GetRobotSoftwareVersion >::value();
  }
  static const char* value(const ::ur_msgs::GetRobotSoftwareVersionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ur_msgs::GetRobotSoftwareVersionResponse> should match
// service_traits::MD5Sum< ::ur_msgs::GetRobotSoftwareVersion >
template<>
struct MD5Sum< ::ur_msgs::GetRobotSoftwareVersionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ur_msgs::GetRobotSoftwareVersion >::value();
  }
  static const char* value(const ::ur_msgs::GetRobotSoftwareVersionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ur_msgs::GetRobotSoftwareVersionResponse> should match
// service_traits::DataType< ::ur_msgs::GetRobotSoftwareVersion >
template<>
struct DataType< ::ur_msgs::GetRobotSoftwareVersionResponse>
{
  static const char* value()
  {
    return DataType< ::ur_msgs::GetRobotSoftwareVersion >::value();
  }
  static const char* value(const ::ur_msgs::GetRobotSoftwareVersionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // UR_MSGS_MESSAGE_GETROBOTSOFTWAREVERSION_H
