// Generated by gencpp from file ur_msgs/SetAnalogOutput.msg
// DO NOT EDIT!


#ifndef UR_MSGS_MESSAGE_SETANALOGOUTPUT_H
#define UR_MSGS_MESSAGE_SETANALOGOUTPUT_H

#include <ros/service_traits.h>


#include <ur_msgs/SetAnalogOutputRequest.h>
#include <ur_msgs/SetAnalogOutputResponse.h>


namespace ur_msgs
{

struct SetAnalogOutput
{

typedef SetAnalogOutputRequest Request;
typedef SetAnalogOutputResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetAnalogOutput
} // namespace ur_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ur_msgs::SetAnalogOutput > {
  static const char* value()
  {
    return "eb3840e5f3632fc236409b92a9250f5b";
  }

  static const char* value(const ::ur_msgs::SetAnalogOutput&) { return value(); }
};

template<>
struct DataType< ::ur_msgs::SetAnalogOutput > {
  static const char* value()
  {
    return "ur_msgs/SetAnalogOutput";
  }

  static const char* value(const ::ur_msgs::SetAnalogOutput&) { return value(); }
};


// service_traits::MD5Sum< ::ur_msgs::SetAnalogOutputRequest> should match
// service_traits::MD5Sum< ::ur_msgs::SetAnalogOutput >
template<>
struct MD5Sum< ::ur_msgs::SetAnalogOutputRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ur_msgs::SetAnalogOutput >::value();
  }
  static const char* value(const ::ur_msgs::SetAnalogOutputRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ur_msgs::SetAnalogOutputRequest> should match
// service_traits::DataType< ::ur_msgs::SetAnalogOutput >
template<>
struct DataType< ::ur_msgs::SetAnalogOutputRequest>
{
  static const char* value()
  {
    return DataType< ::ur_msgs::SetAnalogOutput >::value();
  }
  static const char* value(const ::ur_msgs::SetAnalogOutputRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ur_msgs::SetAnalogOutputResponse> should match
// service_traits::MD5Sum< ::ur_msgs::SetAnalogOutput >
template<>
struct MD5Sum< ::ur_msgs::SetAnalogOutputResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ur_msgs::SetAnalogOutput >::value();
  }
  static const char* value(const ::ur_msgs::SetAnalogOutputResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ur_msgs::SetAnalogOutputResponse> should match
// service_traits::DataType< ::ur_msgs::SetAnalogOutput >
template<>
struct DataType< ::ur_msgs::SetAnalogOutputResponse>
{
  static const char* value()
  {
    return DataType< ::ur_msgs::SetAnalogOutput >::value();
  }
  static const char* value(const ::ur_msgs::SetAnalogOutputResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // UR_MSGS_MESSAGE_SETANALOGOUTPUT_H
