// Generated by gencpp from file ur_msgs/SetForceMode.msg
// DO NOT EDIT!


#ifndef UR_MSGS_MESSAGE_SETFORCEMODE_H
#define UR_MSGS_MESSAGE_SETFORCEMODE_H

#include <ros/service_traits.h>


#include <ur_msgs/SetForceModeRequest.h>
#include <ur_msgs/SetForceModeResponse.h>


namespace ur_msgs
{

struct SetForceMode
{

typedef SetForceModeRequest Request;
typedef SetForceModeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetForceMode
} // namespace ur_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ur_msgs::SetForceMode > {
  static const char* value()
  {
    return "ad1bcbfccfedd053ec6bb7eb365913d8";
  }

  static const char* value(const ::ur_msgs::SetForceMode&) { return value(); }
};

template<>
struct DataType< ::ur_msgs::SetForceMode > {
  static const char* value()
  {
    return "ur_msgs/SetForceMode";
  }

  static const char* value(const ::ur_msgs::SetForceMode&) { return value(); }
};


// service_traits::MD5Sum< ::ur_msgs::SetForceModeRequest> should match
// service_traits::MD5Sum< ::ur_msgs::SetForceMode >
template<>
struct MD5Sum< ::ur_msgs::SetForceModeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ur_msgs::SetForceMode >::value();
  }
  static const char* value(const ::ur_msgs::SetForceModeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ur_msgs::SetForceModeRequest> should match
// service_traits::DataType< ::ur_msgs::SetForceMode >
template<>
struct DataType< ::ur_msgs::SetForceModeRequest>
{
  static const char* value()
  {
    return DataType< ::ur_msgs::SetForceMode >::value();
  }
  static const char* value(const ::ur_msgs::SetForceModeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ur_msgs::SetForceModeResponse> should match
// service_traits::MD5Sum< ::ur_msgs::SetForceMode >
template<>
struct MD5Sum< ::ur_msgs::SetForceModeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ur_msgs::SetForceMode >::value();
  }
  static const char* value(const ::ur_msgs::SetForceModeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ur_msgs::SetForceModeResponse> should match
// service_traits::DataType< ::ur_msgs::SetForceMode >
template<>
struct DataType< ::ur_msgs::SetForceModeResponse>
{
  static const char* value()
  {
    return DataType< ::ur_msgs::SetForceMode >::value();
  }
  static const char* value(const ::ur_msgs::SetForceModeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // UR_MSGS_MESSAGE_SETFORCEMODE_H
